name: 'My Pipeline'
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  tests:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v4
 
      - name: Pull Image
        run: docker pull coherentsolutions/rest-training:2.0
 
      - name: Run 
        run: docker run -d -p 49000:8082 coherentsolutions/rest-training:2.0
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
 
      - name: Run Test
        if: always()
        run: 
          mvn clean test
        continue-on-error: true
 
      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/junitreports/*.xml
          reporter: java-junit
          fail-on-error: true
         
      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report
        uses: simple-elf/allure-report-action@1.7
        if: always()
        id: allure-report
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
 
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
